#!/usr/bin/env ruby

require 'rubygems'
require 'bundler/setup'
require 'system_cat'

include SystemCat

status = Git.status
raise 'Not on master' unless status[:branch] == :master
raise 'Uncommited changes' unless status[:clean]

Git.pull
Shell.run('rspec spec')

version = Version.new('config/version.txt')

Shell.run('gem build status_cat.gemspec')
Shell.run("gem push system_cat-#{version}.gem")

Git.tag(version.to_s)
version.bump
Git.commit("Bumping version to #{version}")

Git.push(:origin, :master)
